### ISSUE TITLE
Problem running tests on Ubuntu Natty

### ISSUE THREAD

**Issue by dasch** [samvincent/rqrcode-rails3#2]
I get the following failure:

```
test_png_request_sends_a_png_as_file(NavigationTest)
    [/home/daniel/Projects/rqrcode-rails3/test/integration/navigation_test.rb:19:in `test_png_request_sends_a_png_as_file'
     activesupport (3.0.7) lib/active_support/testing/setup_and_teardown.rb:67:in `__send__'
     activesupport (3.0.7) lib/active_support/testing/setup_and_teardown.rb:67:in `run'
     activesupport (3.0.7) lib/active_support/callbacks.rb:419:in `_run_setup_callbacks'
     activesupport (3.0.7) lib/active_support/testing/setup_and_teardown.rb:65:in `run']:
<"\211PNG\r\n\032\n\000\000\000\rIHDR\000\000\001k\000\000\001k\001\000\000\000\000?"> expected but was
<"\211PNG\r\n\032\n\000\000\000\rIHDR\000\000\001k\000\000\001k\020\004\000\000\000\355">.
```

**Comment by samvincent** [comment]
Latest version matches against the first 25 chars instead of 30... Not sure if that will fix this. Let me know.

**Comment by dasch** [comment]
Now I get this instead:

```
test_png_request_returns_an_PNG_file(NavigationTest)
    [/home/daniel/Projects/rqrcode-rails3/test/integration/navigation_test.rb:19:in `test_png_request_returns_an_PNG_file'
     activesupport (3.0.7) lib/active_support/testing/setup_and_teardown.rb:67:in `__send__'
     activesupport (3.0.7) lib/active_support/testing/setup_and_teardown.rb:67:in `run'
     activesupport (3.0.7) lib/active_support/callbacks.rb:419:in `_run_setup_callbacks'
     activesupport (3.0.7) lib/active_support/testing/setup_and_teardown.rb:65:in `run']:
<"\211PNG\r\n\032\n\000\000\000\rIHDR\000\000\001k\000\000\001k\001"> expected but was
<"\211PNG\r\n\032\n\000\000\000\rIHDR\000\000\001k\000\000\001k\020">.
```
